### PR TITLE
Remove unnecessary call for resignFisrtResponder

### PR DESCRIPTION
**Pull request by csv8674xn**
This unnecessary resignFirstResponder will result in a zombie object and cause runtime crashes when users try to use 3D Touch

### CODE REVIEW

**Comment by dgattey** [comment]
Unfortunately, none of us have a good understanding as to why we have this code in here, but I'm sure it is/was there for a reason :)

**Comment by csv8674xn** [comment]
the `becomeFirstResponder` ensure the keyboard will be the first responder and the keyboard will still show up after users force touch and drag the name. 

I explored a little bit about the architeture. To expose a flag that is specifically for this change to the application does not seem very reasonable to me and it's exposing the implementation detail inside the library. However, I completely agree that we should have some way to control this change. To leverage it, I would suggest having a flag passed down to the function`cycleFirstResponderStatusWithMode`. Turn it to be `false` to all other case except the one that is causing the crash so that the change can be limited. Besides, since we already know the existing code is crashing the app, the worst case would be we still run into the crash in the same code path, other should not be impacted. In terms of the behavior of the function, it may have impact on auto capitalization. However, in my tests, auto capitalization worked as expected.

**Comment by dgattey** [comment]
Sure, that seems reasonable to me! Thanks for looking at this.

**Comment by Nadohs** [comment]
Through investigation using Zombines memory tool to debug calls to deallocated objects, we found that the cause of the crash was related to calling `resginFirstResponder` and then immediately after calling `becomeFirstResponder` on the same object, during a force touch interaction on the textView. With zombies tool we were able to see that the object being deallocated was `UIKeyboardTextSelectionController`. The full debug output is:
```
[_UIKeyboardTextSelectionController setCursorPosition:]: message sent to deallocated instance
```
We found that first calling resignFirstResponder destroys the UIKeyboardTextSelectionController by creating a new one
```
   0 libobjc.A.dylib -[NSObject release] (UIKeyboardTextSelectionController is released from memory)

   1 UIKit -[UIKeyboardImpl setTextSelectionControllerFromDelegate]
   2 UIKit -[UIKeyboardImpl setDelegate:force:]
   3 UIKit -[UIPeripheralHost(UIKitInternal) _reloadInputViewsForResponder:]
   4 UIKit -[UIResponder _finishResignFirstResponder]
   5 UIKit -[UIResponder resignFirstResponder]
   6 UIKit -[UITextView resignFirstResponder]
   7 HakawaiDemo -[HKWTextView(Plugins) cycleFirstResponderStatusWithMode:cancelAnimation:] /Users/rgfox/Development/open_source_li/Hakawai/Hakawai/Core/HKWTextView+Plugins.m:370
```

When `becomeFirstResponder` is called at the same time a new object `UIKeyboardTextSelectionController` object is created
```
   2 libobjc.A.dylib class_createInstance
   3 libobjc.A.dylib +[NSObject allocWithZone:]
   4 UIKit -[UIKeyboardImpl setTextSelectionControllerFromDelegate]
   5 UIKit -[UIKeyboardImpl setDelegate:force:]
   6 UIKit -[UIPeripheralHost(UIKitInternal) _reloadInputViewsForResponder:]
   7 UIKit -[UIResponder(UIResponderInputViewAdditions) reloadInputViews]
   8 UIKit -[UIResponder becomeFirstResponder]
   9 UIKit -[UIView(Hierarchy) becomeFirstResponder]
  10 UIKit -[UITextView becomeFirstResponder]
  11 HakawaiDemo -[HKWTextView becomeFirstResponder] /Users/rgfox/Development/open_source_li/Hakawai/Hakawai/Core/HKWTextView.m:661
```

When force touch occurs during this it sends a message to the old object reference, which is already dealloced

   crash message with zombies on: 
```
   [_UIKeyboardTextSelectionController setCursorPosition:]: message sent to deallocated instance
```

````
   2 UIKit -[_UIKeyboardTextSelectionController setCursorPosition:]
   3 UIKit __112-[_UIKeyboardTextSelectionGestureCluster _granularityExpandingGestureWithTimeInterval:timeGranularity:isMidPan:]_block_invoke
   4 UIKit -[UIKeyboardTaskEntry execute:]
   5 UIKit -[UIKeyboardTaskQueue continueExecutionOnMainThread]
   6 UIKit -[_UIKeyboardTextSelectionGestureCluster _granularityExpandingGestureWithTimeInterval:timeGranularity:isMidPan:]
   7 UIKit -[_UIKeyboardBasedTextSelectionGestureCluster oneFingerForcePress:]
   8 UIKit -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:]
   9 UIKit _UIGestureRecognizerSendTargetActions
  10 UIKit -[UIGestureRecognizer _forceLevelClassifier:currentForceLevelDidChange:]
  11 UIKit -[_UIForceLevelClassifier setCurrentForceLevel:]
```
Our best guess about what is going on, is that some intermediary object for keyboard or force touch keeps a reference to the old `UIKeyboardTextSelectionController` object, which is not updated when `becomeFirstResponder` is triggered. Causing a crash

Solution:
--------
The fix we found for this issue was to simply remove the `resignFirstResponder` call.

**Pull request merged**
